### ISSUE TITLE
It no longer recognizes 7z or the kindlegen binary.

### ISSUE THREAD

**Issue by mluizvitor** [flathub/io.github.ciromattia.kcc#1]
After the last [commit](https://github.com/flathub/io.github.ciromattia.kcc/commit/e752f44dea379a8287ffcedd8cd999b21bea2690), KCC doesn't work as before. It no longer recognizes **7z** or the **kindlegen** binary.

![Captura de tela de 2021-12-30 10-50-21](https://user-images.githubusercontent.com/57257682/147757904-89f4addb-2b52-4c65-b233-82b118536e18.png)
![Captura de tela de 2021-12-30 10-59-58](https://user-images.githubusercontent.com/57257682/147758522-589ddefb-5a50-431f-8344-223a1b48e44d.png)

**Comment by catsout** [comment]
Sorry, I include the test case manifest, fixed.  
If you are in hurry, try https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading
