### ISSUE TITLE
Not enough disk space to perform the conversion. 

### ISSUE THREAD

**Issue by tsopeh** [flathub/io.github.ciromattia.kcc#4]
I get this error message each time I try converting some relatively large .zip archive (e.g. larger than 1GB).

This [workaround](https://gitlab.gnome.org/World/lollypop/-/issues/2706#workaround) worked for me. 

Alternatively, the same workaround can also be applied via [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), like in the following image.
![image](https://user-images.githubusercontent.com/37545996/182441674-570f972e-2df8-44a1-a202-f27c9a59fb1b.png)

Is it possible for this permission (access to `/tmp`) to be set **by default**?

After enabling this permission, the conversion goes through and everything works fine for some time. After, let's say three or four such conversions the same error message appears again, but for a different reason, I think. It appears that KCC doesn't clear after itself when conversion is done This means that there are many images left in the `/tmp` directory after each conversion. If I manually clear these images via [BleachBit](https://www.bleachbit.org/) or if I restart my PC, I can do conversion successfully, until the same issue appears again. I don't know if this issue is related to flatpak or upstream.

**Comment by catsout** [comment]
`TMPDIR` is set to `/var/tmp` which is bind mounted from `$XDG_CACHE_HOME/tmp`.
